version: "3.7"

networks:
  frappe-network:
    name : frappe-network
    external: true

volumes:
  frappe13-mariadb-vol:
    external: true
    name: frappe13-mariadb-vol
  frappe13-redis-cache-data:
    external: true
    name: frappe13-redis-cache-data
  frappe13-redis-queue-data:
    external: true
    name: frappe13-redis-queue-data
  frappe13-redis-socketio-data:
    external: true
    name: frappe13-redis-socketio-data
  # postgresql-vol:

services:
  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ../../frappe_docker_13/installation/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - frappe13-mariadb-vol:/var/lib/mysql
    networks:
      - frappe-network

  # Enable PostgreSQL only if you use it, see development/README.md for more information.
  # postgresql:
  #   image: postgres:11.8
  #   restart: on-failure
  #   environment:
  #     - POSTGRES_PASSWORD=123
  #   volumes:
  #     - postgresql-vol:/var/lib/postgresql/data

  redis-cache:
    image: redis:alpine
    volumes:
      - frappe13-redis-cache-data:/data
    networks:
      - frappe-network

  redis-queue:
    image: redis:alpine
    volumes:
      - frappe13-redis-queue-data:/data
    networks:
      - frappe-network

  redis-socketio:
    image: redis:alpine
    volumes:
      - frappe13-redis-socketio-data:/data
    networks:
      - frappe-network

  frappe:
    image: frappe/bench:latest
    command: sleep infinity
    volumes:
      - ../../frappe_docker_13:/workspace
      - /home/${USER}/.ssh/id_rsa:/home/frappe/.ssh/id_rsa
      - /home/${USER}/.ssh/id_rsa.pub:/home/frappe/.ssh/id_rsa.pub
      - /home/${USER}/.ssh/known_hosts:/home/frappe/.ssh/known_hosts
    working_dir: /workspace/development/
    ports:
      - "8000-8005:8000-8005"
      - "9000-9005:9000-9005"
    networks:
      - frappe-network

  # adminer:
  # image: adminer
  # depends_on:
  # - mariadb
  # ports:
  # - 7000:8080
  # networks:
  # - frappe-network
