version: "3.7"

networks:
  frappe-network:
    name: frappe-network
    external: true

volumes:
  frappe12-mariadb-vol:
    external: true
    name: frappe12-mariadb-vol
  frappe12-redis-cache-data:
    external: true
    name: frappe12-redis-cache-data
  frappe12-redis-queue-data:
    external: true
    name: frappe12-redis-queue-data
  frappe12-redis-socketio-data:
    external: true
    name: frappe12-redis-socketio-data
  # postgresql-vol:

services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
      - --max_allowed_packet=512M
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
      # Sometimes db initialization takes longer than 10 seconds and site-creator goes away.
      # Frappe doesn't use CONVERT_TZ() function that requires time zone info, so we can just skip it.
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - frappe12-mariadb-vol:/var/lib/mysql
    networks:
      - frappe-network
    ports:
      - "33066:3306"
      - # Enable PostgreSQL only if you use it, see development/README.md for more information.
        # postgresql:
        #   image: postgres:11.8
        #   restart: on-failure
        #   environment:
        #     - POSTGRES_PASSWORD=123
        #   volumes:
        #     - postgresql-vol:/var/lib/postgresql/data

  redis-cache:
    image: redis:alpine
    volumes:
      - frappe12-redis-cache-data:/data
    networks:
      - frappe-network

  redis-queue:
    image: redis:alpine
    volumes:
      - frappe12-redis-queue-data:/data
    networks:
      - frappe-network

  redis-socketio:
    image: redis:alpine
    volumes:
      - frappe12-redis-socketio-data:/data
    networks:
      - frappe-network

  frappe:
    image: frappe/bench:latest
    command: sleep infinity
    volumes:
      - ../../frappe_docker_12:/workspace
      - /home/${USER}/.ssh/id_rsa:/home/frappe/.ssh/id_rsa
      - /home/${USER}/.ssh/id_rsa.pub:/home/frappe/.ssh/id_rsa.pub
      - /home/${USER}/.ssh/known_hosts:/home/frappe/.ssh/known_hosts
      - /home/${USER}/.bash_history:/home/frappe/.bash_history
      - /home/${USER}/.gitconfig:/home/frappe/.gitconfig
    working_dir: /workspace/development/
    ports:
      - "8000-8005:8000-8005"
      - "9000-9005:9000-9005"
    networks:
      - frappe-network

  # adminer:
  # image: adminer
  # depends_on:
  # - mariadb
  # ports:
  # - 7000:8080
  # networks:
  # - frappe-network
